[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/ffp-accueil.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/ffp-accueil.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/ffp-sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"
